Ignore unexpected_cfgs lint for tests
```
error: unexpected `cfg` condition name: `rustfmt`
 --> src/gen/assert_impl.rs:6:13
  |
6 | #![cfg_attr(rustfmt, rustfmt::skip)]
  |             ^^^^^^^
```

Due to https://github.com/rust-lang/rust/issues/124735, we cannot
disable this lint at module-level.